version = 1

exclude_patterns = [
  "**/demo_code.py",
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  cyclomatic_complexity_threshold = "low"

[[transformers]]
name = "black"
